# 📚 Web Scraping Pipeline: Books Data

## Objective
Scrape books data (title, price, rating, availability) from a public website and store it in a structured format.

## Use Cases
- Web scraping for analytics
- Price monitoring
- Market analysis

## Tech Stack
- Python
- requests
- BeautifulSoup
- pandas
- datetime

In [ ]:
# import the important libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

In [2]:
# fetch HTML content using url
url = 'https://books.toscrape.com/'
response = requests.get(url)
response

In [3]:
# parse HTML using BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [4]:
# Total number of pages
no_of_pages = int(soup.select('.pager li.current')[0].text.strip().split()[-1])
print(f'There are total {no_of_pages} pages.')

There are total 50 pages.

In [5]:
# Extracting data for all pages

data_list = []
base_url = 'https://books.toscrape.com/catalogue/page-{}.html'
for page in range(1, no_of_pages + 1):
    url = base_url.format(page)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    for i in soup.select('ol.row li'):
        data_dict = {}
        data_dict['name'] = i.select('h3')[-1].text.strip()
        data_dict['price'] = i.select('.product_price p.price_color')[0].text.strip().replace('Â£', '')
        data_dict['rating'] = i.select('p.star-rating')[0].get('class')[-1]
        data_dict['stock_status'] = i.select('p.instock.availability')[0].text.strip()
        data_dict['timestamp'] = datetime.now()
        data_list.append(data_dict)
        
data_list

[{'name': 'A Light in the ...',
  'price': '51.77',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 740876)},
 {'name': 'Tipping the Velvet',
  'price': '53.74',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 741312)},
 {'name': 'Soumission',
  'price': '50.10',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 741710)},
 {'name': 'Sharp Objects',
  'price': '47.82',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 742102)},
 {'name': 'Sapiens: A Brief History ...',
  'price': '54.23',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 742500)},
 {'name': 'The Requiem Red',
  'price': '22.65',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 742878)},
 {'name': 'The Dirty Little Secrets ...',
  'price': '33.34',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 743252)},
 {'name': 'The Coming Woman: A ...',
  'price': '17.93',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 743623)},
 {'name': 'The Boys in the ...',
  'price': '22.60',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 743994)},
 {'name': 'The Black Maria',
  'price': '52.15',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 744364)},
 {'name': 'Starving Hearts (Triangular Trade ...',
  'price': '13.99',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 744744)},
 {'name': "Shakespeare's Sonnets",
  'price': '20.66',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 745120)},
 {'name': 'Set Me Free',
  'price': '17.46',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 745574)},
 {'name': "Scott Pilgrim's Precious Little ...",
  'price': '52.29',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 745954)},
 {'name': 'Rip it Up and ...',
  'price': '35.02',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 746324)},
 {'name': 'Our Band Could Be ...',
  'price': '57.25',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 746699)},
 {'name': 'Olio',
  'price': '23.88',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 747054)},
 {'name': 'Mesaerion: The Best Science ...',
  'price': '37.59',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 747410)},
 {'name': 'Libertarianism for Beginners',
  'price': '51.33',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 747768)},
 {'name': "It's Only the Himalayas",
  'price': '45.17',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 36, 748120)},
 {'name': 'In Her Wake',
  'price': '12.84',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 738515)},
 {'name': 'How Music Works',
  'price': '37.32',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 738937)},
 {'name': 'Foolproof Preserving: A Guide ...',
  'price': '30.52',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 739342)},
 {'name': 'Chase Me (Paris Nights ...',
  'price': '25.27',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 739734)},
 {'name': 'Black Dust',
  'price': '34.53',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 740128)},
 {'name': 'Birdsong: A Story in ...',
  'price': '54.64',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 740525)},
 {'name': "America's Cradle of Quarterbacks: ...",
  'price': '22.50',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 740927)},
 {'name': 'Aladdin and His Wonderful ...',
  'price': '53.13',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 741321)},
 {'name': 'Worlds Elsewhere: Journeys Around ...',
  'price': '40.30',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 741702)},
 {'name': 'Wall and Piece',
  'price': '44.18',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 742080)},
 {'name': 'The Four Agreements: A ...',
  'price': '17.66',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 742459)},
 {'name': 'The Five Love Languages: ...',
  'price': '31.05',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 742840)},
 {'name': 'The Elephant Tree',
  'price': '23.82',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 743220)},
 {'name': 'The Bear and the ...',
  'price': '36.89',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 743603)},
 {'name': "Sophie's World",
  'price': '15.94',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 743996)},
 {'name': 'Penny Maybe',
  'price': '33.29',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 744371)},
 {'name': 'Maude (1883-1993):She Grew Up ...',
  'price': '18.02',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 744739)},
 {'name': 'In a Dark, Dark ...',
  'price': '19.63',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 745111)},
 {'name': 'Behind Closed Doors',
  'price': '52.22',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 745556)},
 {'name': "You can't bury them ...",
  'price': '33.63',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 38, 745935)},
 {'name': 'Slow States of Collapse: ...',
  'price': '57.31',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 915480)},
 {'name': 'Reasons to Stay Alive',
  'price': '26.41',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 915886)},
 {'name': 'Private Paris (Private #10)',
  'price': '47.61',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 916280)},
 {'name': '#HigherSelfie: Wake Up Your ...',
  'price': '23.11',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 916677)},
 {'name': 'Without Borders (Wanderlove #1)',
  'price': '45.07',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 917076)},
 {'name': 'When We Collided',
  'price': '31.77',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 917468)},
 {'name': 'We Love You, Charlie ...',
  'price': '50.27',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 917860)},
 {'name': 'Untitled Collection: Sabbath Poems ...',
  'price': '14.27',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 918264)},
 {'name': 'Unseen City: The Majesty ...',
  'price': '44.18',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 918736)},
 {'name': 'Unicorn Tracks',
  'price': '18.78',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 919147)},
 {'name': 'Unbound: How Eight Technologies ...',
  'price': '25.52',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 919544)},
 {'name': 'Tsubasa: WoRLD CHRoNiCLE 2 ...',
  'price': '16.28',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 919929)},
 {'name': 'Throwing Rocks at the ...',
  'price': '31.12',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 920312)},
 {'name': 'This One Summer',
  'price': '19.49',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 920704)},
 {'name': 'Thirst',
  'price': '17.27',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 921090)},
 {'name': 'The Torch Is Passed: ...',
  'price': '19.09',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 921491)},
 {'name': 'The Secret of Dreadwillow ...',
  'price': '56.13',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 921887)},
 {'name': 'The Pioneer Woman Cooks: ...',
  'price': '56.41',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 922387)},
 {'name': 'The Past Never Ends',
  'price': '56.50',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 922782)},
 {'name': 'The Natural History of ...',
  'price': '45.22',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 46, 923164)},
 {'name': 'The Nameless City (The ...',
  'price': '38.16',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 787366)},
 {'name': 'The Murder That Never ...',
  'price': '54.11',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 787830)},
 {'name': 'The Most Perfect Thing: ...',
  'price': '42.96',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 788254)},
 {'name': 'The Mindfulness and Acceptance ...',
  'price': '23.89',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 788637)},
 {'name': 'The Life-Changing Magic of ...',
  'price': '16.77',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 789049)},
 {'name': 'The Inefficiency Assassin: Time ...',
  'price': '20.59',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 789433)},
 {'name': 'The Gutsy Girl: Escapades ...',
  'price': '37.13',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 789825)},
 {'name': 'The Electric Pencil: Drawings ...',
  'price': '56.06',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 790210)},
 {'name': 'The Death of Humanity: ...',
  'price': '58.11',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 790597)},
 {'name': 'The Bulletproof Diet: Lose ...',
  'price': '49.05',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 790979)},
 {'name': 'The Art Forger',
  'price': '40.76',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 791363)},
 {'name': 'The Age of Genius: ...',
  'price': '19.73',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 791747)},
 {'name': "The Activist's Tao Te ...",
  'price': '32.24',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 792134)},
 {'name': 'Spark Joy: An Illustrated ...',
  'price': '41.83',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 792513)},
 {'name': 'Soul Reader',
  'price': '39.58',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 792894)},
 {'name': 'Security',
  'price': '39.25',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 793334)},
 {'name': 'Saga, Volume 6 (Saga ...',
  'price': '25.02',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 793758)},
 {'name': 'Saga, Volume 5 (Saga ...',
  'price': '51.04',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 794188)},
 {'name': 'Reskilling America: Learning to ...',
  'price': '19.83',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 794561)},
 {'name': 'Rat Queens, Vol. 3: ...',
  'price': '50.40',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 53, 794931)},
 {'name': 'Princess Jellyfish 2-in-1 Omnibus, ...',
  'price': '13.61',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 528145)},
 {'name': 'Princess Between Worlds (Wide-Awake ...',
  'price': '13.34',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 528616)},
 {'name': 'Pop Gun War, Volume ...',
  'price': '18.97',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 529040)},
 {'name': 'Political Suicide: Missteps, Peccadilloes, ...',
  'price': '36.28',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 529454)},
 {'name': 'Patience',
  'price': '10.16',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 529876)},
 {'name': 'Outcast, Vol. 1: A ...',
  'price': '15.44',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 530287)},
 {'name': 'orange: The Complete Collection ...',
  'price': '48.41',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 530694)},
 {'name': 'Online Marketing for Busy ...',
  'price': '46.35',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 531095)},
 {'name': 'On a Midnight Clear',
  'price': '14.07',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 531499)},
 {'name': 'Obsidian (Lux #1)',
  'price': '14.86',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 531918)},
 {'name': 'My Paris Kitchen: Recipes ...',
  'price': '33.37',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 532309)},
 {'name': 'Masks and Shadows',
  'price': '56.40',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 532703)},
 {'name': 'Mama Tried: Traditional Italian ...',
  'price': '14.02',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 533093)},
 {'name': 'Lumberjanes, Vol. 2: Friendship ...',
  'price': '46.91',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 533485)},
 {'name': 'Lumberjanes, Vol. 1: Beware ...',
  'price': '45.61',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 533874)},
 {'name': 'Lumberjanes Vol. 3: A ...',
  'price': '19.92',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 534268)},
 {'name': 'Layered: Baking, Building, and ...',
  'price': '40.11',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 534656)},
 {'name': 'Judo: Seven Steps to ...',
  'price': '53.90',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 535049)},
 {'name': 'Join',
  'price': '35.67',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 535492)},
 {'name': 'In the Country We ...',
  'price': '22.00',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 57, 535887)},
 {'name': 'Immunity: How Elie Metchnikoff ...',
  'price': '57.36',
  'rating': 'Five',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 579701)},
 {'name': 'I Hate Fairyland, Vol. ...',
  'price': '29.17',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 580113)},
 {'name': 'I am a Hero ...',
  'price': '54.63',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 580527)},
 {'name': 'How to Be Miserable: ...',
  'price': '46.03',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 580932)},
 {'name': 'Her Backup Boyfriend (The ...',
  'price': '33.97',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 581333)},
 {'name': 'Giant Days, Vol. 2 ...',
  'price': '22.11',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 581739)},
 {'name': 'Forever and Forever: The ...',
  'price': '29.69',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 582145)},
 {'name': 'First and First (Five ...',
  'price': '15.97',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 582548)},
 {'name': 'Fifty Shades Darker (Fifty ...',
  'price': '21.96',
  'rating': 'One',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 582944)},
 {'name': 'Everydata: The Misinformation Hidden ...',
  'price': '54.35',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 583348)},
 {'name': "Don't Be a Jerk: ...",
  'price': '37.97',
  'rating': 'Two',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 583747)},
 {'name': 'Danganronpa Volume 1',
  'price': '51.99',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 584144)},
 {'name': 'Crown of Midnight (Throne ...',
  'price': '43.29',
  'rating': 'Three',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 584544)},
 {'name': 'Codename Baboushka, Volume 1: ...',
  'price': '36.72',
  'rating': 'Four',
  'stock_status': 'In stock',
  'timestamp': datetime.datetime(2026, 5, 4, 21, 43, 59, 584942)},
 {'name': 'Camp Midnight',

In [6]:
# Converting the extracted data into pandas DataFrame
df = pd.DataFrame(data_list)
df

,name,price,rating,stock_status,timestamp
0,A Light in the ...,51.77,Three,In stock,2026-05-04 21:43:36.740876
1,Tipping the Velvet,53.74,One,In stock,2026-05-04 21:43:36.741312
2,Soumission,50.10,One,In stock,2026-05-04 21:43:36.741710
3,Sharp Objects,47.82,Four,In stock,2026-05-04 21:43:36.742102
4,Sapiens: A Brief History ...,54.23,Five,In stock,2026-05-04 21:43:36.742500
...,...,...,...,...,...
995,Alice in Wonderland (Alice's ...,55.53,One,In stock,2026-05-04 21:48:28.014379
996,"Ajin: Demi-Human, Volume 1 ...",57.06,Four,In stock,2026-05-04 21:48:28.014758
997,A Spy's Devotion (The ...,16.97,Five,In stock,2026-05-04 21:48:28.015137
998,1st to Die (Women's ...,53.98,One,In stock,2026-05-04 21:48:28.015522
999,"1,000 Places to See ...",26.08,Five,In stock,2026-05-04 21:48:28.015889

In [7]:
# Shape of the data
print(f'There are {df.shape[0]} rows and {df.shape[1]} columns in the data.')

There are 1000 rows and 5 columns in the data.

In [8]:
# Data type of each column
df.dtypes

name                       str
price                      str
rating                     str
stock_status               str
timestamp       datetime64[us]
dtype: object

In [9]:
# convert the data type of 'Price' from str to float
df['price'] = df['price'].astype('float')
df.dtypes

name                       str
price                  float64
rating                     str
stock_status               str
timestamp       datetime64[us]
dtype: object

In [10]:
# Let's map the ratings

df["rating"] = df["rating"].map({'One':1,
                                 'Two':2,
                                 'Three':3,
                                 'Four':4,
                                 'Five': 5})
df.head()

,name,price,rating,stock_status,timestamp
0,A Light in the ...,51.77,3,In stock,2026-05-04 21:43:36.740876
1,Tipping the Velvet,53.74,1,In stock,2026-05-04 21:43:36.741312
2,Soumission,50.10,1,In stock,2026-05-04 21:43:36.741710
3,Sharp Objects,47.82,4,In stock,2026-05-04 21:43:36.742102
4,Sapiens: A Brief History ...,54.23,5,In stock,2026-05-04 21:43:36.742500

In [11]:
# info of the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          1000 non-null   str
 1   price         1000 non-null   float64
 2   rating        1000 non-null   int64
 3   stock_status  1000 non-null   str
 4   timestamp     1000 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 39.2 KB

In [12]:
# Statistical summary of the data
df.describe()

            price       rating                   timestamp
count  1000.00000  1000.000000                        1000
mean     35.07035     2.923000  2026-05-04 21:46:09.411329
min      10.00000     1.000000  2026-05-04 21:43:36.740876
25%      22.10750     2.000000  2026-05-04 21:44:44.334128
50%      35.98000     3.000000  2026-05-04 21:46:32.632915
75%      47.45750     4.000000  2026-05-04 21:47:24.763912
max      59.99000     5.000000  2026-05-04 21:48:28.015889
std      14.44669     1.434967                         NaN

In [13]:
# export this data to csv
df.to_csv("books_to_scrape.csv", index=False)

In [14]:
# no. of unique books
print(f'There are {df['name'].nunique()} unique books.')

There are 992 unique books.

In [15]:
# Top 10 Expensive books
df.sort_values(by = 'price', ascending = False).head(10)

,name,price,rating,stock_status,timestamp
648,The Perfect Play (Play ...,59.99,3,In stock,2026-05-04 21:47:12.314588
617,Last One Home (New ...,59.98,3,In stock,2026-05-04 21:47:08.960278
860,Civilization and Its Discontents,59.95,2,In stock,2026-05-04 21:47:52.645683
560,The Barefoot Contessa Cookbook,59.92,5,In stock,2026-05-04 21:46:56.696376
366,The Diary of a ...,59.90,3,In stock,2026-05-04 21:45:29.066956
657,The Bone Hunters (Lexy ...,59.71,3,In stock,2026-05-04 21:47:12.317770
133,Thomas Jefferson and the ...,59.64,1,In stock,2026-05-04 21:44:01.886580
387,Boar Island (Anna Pigeon ...,59.48,3,In stock,2026-05-04 21:45:31.621904
549,The Man Who Mistook ...,59.45,4,In stock,2026-05-04 21:46:48.728861
393,The Improbability of Love,59.45,1,In stock,2026-05-04 21:45:31.624370

In [16]:
# Top 10 Cheapest books
df.sort_values(by = 'price', ascending = True).head(10)

,name,price,rating,stock_status,timestamp
638,An Abundance of Katherines,10.00,5,In stock,2026-05-04 21:47:10.638510
501,The Origin of Species,10.01,4,In stock,2026-05-04 21:46:42.504771
716,The Tipping Point: How ...,10.02,2,In stock,2026-05-04 21:47:20.479191
84,Patience,10.16,3,In stock,2026-05-04 21:43:57.529876
302,Greek Mythic History,10.23,5,In stock,2026-05-04 21:45:01.833836
558,The Fellowship of the ...,10.27,2,In stock,2026-05-04 21:46:48.732267
479,History of Beauty,10.29,4,In stock,2026-05-04 21:46:14.499324
242,The Lucifer Effect: Understanding ...,10.40,1,In stock,2026-05-04 21:44:44.331290
434,NaNo What Now? Finding ...,10.41,4,In stock,2026-05-04 21:45:44.839545
274,Pet Sematary,10.56,3,In stock,2026-05-04 21:44:57.355690

In [17]:
# Rating Analysis
print('Average Price by Rating')
df.groupby('rating')['price'].mean()

Average Price by Rating

rating
1    34.561195
2    34.810918
3    34.692020
4    36.093296
5    35.374490
Name: price, dtype: float64

In [18]:
print('No. of books by rating')
df.rating.value_counts().sort_values(ascending = False)

No. of books by rating

rating
1    226
3    203
5    196
2    196
4    179
Name: count, dtype: int64

In [19]:
# stock status
df['stock_status'].value_counts()

stock_status
In stock    1000
Name: count, dtype: int64

**All 1000 books are in stock.**

## Key Learnings

- Handling pagination in web scraping
- Parsing structured HTML using BeautifulSoup
- Data cleaning and transformation using pandas