# Books Web Scraping using Python

## 1. Import Libraries

In [1]:
# import the important libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

## 2. Fetch Website Content

In [2]:
# fetch HTML content using url
url = 'https://books.toscrape.com/'
response = requests.get(url)
response.status_code

200

## 3. Parse HTML using BeautifulSoup

In [3]:
# parse HTML using BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')
print(soup.title.text)

    All products | Books to Scrape - Sandbox

## 4. Crawl Books Across Multiple Pages

In [4]:
# Define a function to recursively crawl all available pages

data_list = []
def crawl_next_page(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    for i in soup.select('ol.row li'):
        data_dict = {}

        # extract name, price, rating and stock_status
        data_dict['name'] = i.select('h3')[-1].text.strip()
        data_dict['price'] = i.select('.product_price p.price_color')[0].text.strip().replace('Â£', '')
        data_dict['rating'] = i.select('p.star-rating')[0].get('class')[-1]
        data_dict['stock_status'] = i.select('p.instock.availability')[0].text.strip()
        data_list.append(data_dict)
        
    # next page button
    if soup.select_one('li.next a'):
        if 'catalogue' in soup.select_one('li.next a').get('href'):
            next_url = 'https://books.toscrape.com/' + soup.select_one('li.next a').get('href')
        else:
            next_url = 'https://books.toscrape.com/catalogue/' + soup.select_one('li.next a').get('href')

        # calling recursive function
        crawl_next_page(next_url)

    return data_list

In [5]:
# Let's start crawling
crawl_next_page('https://books.toscrape.com/')

[{'name': 'A Light in the ...',
  'price': '51.77',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Tipping the Velvet',
  'price': '53.74',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Soumission',
  'price': '50.10',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Sharp Objects',
  'price': '47.82',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Sapiens: A Brief History ...',
  'price': '54.23',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'The Requiem Red',
  'price': '22.65',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Dirty Little Secrets ...',
  'price': '33.34',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Coming Woman: A ...',
  'price': '17.93',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'The Boys in the ...',
  'price': '22.60',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Black Maria',
  'price': '52.15',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Starving Hearts (Triangular Trade ...',
  'price': '13.99',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': "Shakespeare's Sonnets",
  'price': '20.66',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Set Me Free',
  'price': '17.46',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': "Scott Pilgrim's Precious Little ...",
  'price': '52.29',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Rip it Up and ...',
  'price': '35.02',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Our Band Could Be ...',
  'price': '57.25',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Olio',
  'price': '23.88',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Mesaerion: The Best Science ...',
  'price': '37.59',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Libertarianism for Beginners',
  'price': '51.33',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': "It's Only the Himalayas",
  'price': '45.17',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'In Her Wake',
  'price': '12.84',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'How Music Works',
  'price': '37.32',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Foolproof Preserving: A Guide ...',
  'price': '30.52',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Chase Me (Paris Nights ...',
  'price': '25.27',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Black Dust',
  'price': '34.53',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Birdsong: A Story in ...',
  'price': '54.64',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': "America's Cradle of Quarterbacks: ...",
  'price': '22.50',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Aladdin and His Wonderful ...',
  'price': '53.13',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Worlds Elsewhere: Journeys Around ...',
  'price': '40.30',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Wall and Piece',
  'price': '44.18',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Four Agreements: A ...',
  'price': '17.66',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'The Five Love Languages: ...',
  'price': '31.05',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'The Elephant Tree',
  'price': '23.82',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'The Bear and the ...',
  'price': '36.89',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': "Sophie's World",
  'price': '15.94',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Penny Maybe',
  'price': '33.29',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Maude (1883-1993):She Grew Up ...',
  'price': '18.02',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'In a Dark, Dark ...',
  'price': '19.63',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Behind Closed Doors',
  'price': '52.22',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': "You can't bury them ...",
  'price': '33.63',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Slow States of Collapse: ...',
  'price': '57.31',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Reasons to Stay Alive',
  'price': '26.41',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Private Paris (Private #10)',
  'price': '47.61',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': '#HigherSelfie: Wake Up Your ...',
  'price': '23.11',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Without Borders (Wanderlove #1)',
  'price': '45.07',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'When We Collided',
  'price': '31.77',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'We Love You, Charlie ...',
  'price': '50.27',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Untitled Collection: Sabbath Poems ...',
  'price': '14.27',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Unseen City: The Majesty ...',
  'price': '44.18',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Unicorn Tracks',
  'price': '18.78',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Unbound: How Eight Technologies ...',
  'price': '25.52',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Tsubasa: WoRLD CHRoNiCLE 2 ...',
  'price': '16.28',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Throwing Rocks at the ...',
  'price': '31.12',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'This One Summer',
  'price': '19.49',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Thirst',
  'price': '17.27',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'The Torch Is Passed: ...',
  'price': '19.09',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Secret of Dreadwillow ...',
  'price': '56.13',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Pioneer Woman Cooks: ...',
  'price': '56.41',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Past Never Ends',
  'price': '56.50',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Natural History of ...',
  'price': '45.22',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'The Nameless City (The ...',
  'price': '38.16',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Murder That Never ...',
  'price': '54.11',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'The Most Perfect Thing: ...',
  'price': '42.96',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Mindfulness and Acceptance ...',
  'price': '23.89',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Life-Changing Magic of ...',
  'price': '16.77',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'The Inefficiency Assassin: Time ...',
  'price': '20.59',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'The Gutsy Girl: Escapades ...',
  'price': '37.13',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Electric Pencil: Drawings ...',
  'price': '56.06',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Death of Humanity: ...',
  'price': '58.11',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Bulletproof Diet: Lose ...',
  'price': '49.05',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'The Art Forger',
  'price': '40.76',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'The Age of Genius: ...',
  'price': '19.73',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': "The Activist's Tao Te ...",
  'price': '32.24',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Spark Joy: An Illustrated ...',
  'price': '41.83',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Soul Reader',
  'price': '39.58',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Security',
  'price': '39.25',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Saga, Volume 6 (Saga ...',
  'price': '25.02',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Saga, Volume 5 (Saga ...',
  'price': '51.04',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Reskilling America: Learning to ...',
  'price': '19.83',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Rat Queens, Vol. 3: ...',
  'price': '50.40',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Princess Jellyfish 2-in-1 Omnibus, ...',
  'price': '13.61',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Princess Between Worlds (Wide-Awake ...',
  'price': '13.34',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Pop Gun War, Volume ...',
  'price': '18.97',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Political Suicide: Missteps, Peccadilloes, ...',
  'price': '36.28',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Patience',
  'price': '10.16',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Outcast, Vol. 1: A ...',
  'price': '15.44',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'orange: The Complete Collection ...',
  'price': '48.41',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Online Marketing for Busy ...',
  'price': '46.35',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'On a Midnight Clear',
  'price': '14.07',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Obsidian (Lux #1)',
  'price': '14.86',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'My Paris Kitchen: Recipes ...',
  'price': '33.37',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Masks and Shadows',
  'price': '56.40',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Mama Tried: Traditional Italian ...',
  'price': '14.02',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Lumberjanes, Vol. 2: Friendship ...',
  'price': '46.91',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Lumberjanes, Vol. 1: Beware ...',
  'price': '45.61',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Lumberjanes Vol. 3: A ...',
  'price': '19.92',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Layered: Baking, Building, and ...',
  'price': '40.11',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Judo: Seven Steps to ...',
  'price': '53.90',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Join',
  'price': '35.67',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'In the Country We ...',
  'price': '22.00',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Immunity: How Elie Metchnikoff ...',
  'price': '57.36',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'I Hate Fairyland, Vol. ...',
  'price': '29.17',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'I am a Hero ...',
  'price': '54.63',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'How to Be Miserable: ...',
  'price': '46.03',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Her Backup Boyfriend (The ...',
  'price': '33.97',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Giant Days, Vol. 2 ...',
  'price': '22.11',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Forever and Forever: The ...',
  'price': '29.69',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'First and First (Five ...',
  'price': '15.97',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Fifty Shades Darker (Fifty ...',
  'price': '21.96',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Everydata: The Misinformation Hidden ...',
  'price': '54.35',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': "Don't Be a Jerk: ...",
  'price': '37.97',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Danganronpa Volume 1',
  'price': '51.99',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Crown of Midnight (Throne ...',
  'price': '43.29',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Codename Baboushka, Volume 1: ...',
  'price': '36.72',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Camp Midnight',
  'price': '17.08',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Call the Nurse: True ...',
  'price': '29.14',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Burning',
  'price': '28.81',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Bossypants',
  'price': '49.46',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Bitch Planet, Vol. 1: ...',
  'price': '37.92',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Avatar: The Last Airbender: ...',
  'price': '28.09',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Algorithms to Live By: ...',
  'price': '30.81',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'A World of Flavor: ...',
  'price': '42.95',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'A Piece of Sky, ...',
  'price': '56.76',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'A Murder in Time',
  'price': '16.64',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'A Flight of Arrows ...',
  'price': '55.53',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'A Fierce and Subtle ...',
  'price': '28.13',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'A Court of Thorns ...',
  'price': '52.37',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': '(Un)Qualified: How God Uses ...',
  'price': '54.00',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'You Are What You ...',
  'price': '21.87',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': "William Shakespeare's Star Wars: ...",
  'price': '43.30',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Tuesday Nights in 1980',
  'price': '21.04',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Tracing Numbers on a ...',
  'price': '41.60',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Throne of Glass (Throne ...',
  'price': '35.07',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Thomas Jefferson and the ...',
  'price': '59.64',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Thirteen Reasons Why',
  'price': '52.72',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The White Cat and ...',
  'price': '58.08',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Wedding Dress',
  'price': '24.12',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Vacationers',
  'price': '42.15',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Third Wave: An ...',
  'price': '12.61',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'The Stranger',
  'price': '17.44',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Shadow Hero (The ...',
  'price': '33.14',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Secret (The Secret ...',
  'price': '27.37',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Regional Office Is ...',
  'price': '51.36',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'The Psychopath Test: A ...',
  'price': '36.00',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'The Project',
  'price': '10.65',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Power of Now: ...',
  'price': '43.54',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': "The Omnivore's Dilemma: A ...",
  'price': '38.21',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'The Nerdy Nummies Cookbook: ...',
  'price': '37.34',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'The Murder of Roger ...',
  'price': '44.10',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The Mistake (Off-Campus #2)',
  'price': '43.29',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': "The Matchmaker's Playbook (Wingmen ...",
  'price': '55.85',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Love and Lemons ...',
  'price': '37.60',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'The Long Shadow of ...',
  'price': '10.97',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Kite Runner',
  'price': '41.82',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'The House by the ...',
  'price': '36.95',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Glittering Court (The ...',
  'price': '44.28',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Girl on the ...',
  'price': '55.02',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'The Genius of Birds',
  'price': '17.24',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Emerald Mystery',
  'price': '23.15',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'The Cookies & Cups ...',
  'price': '41.25',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'The Bridge to Consciousness: ...',
  'price': '32.00',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': "The Artist's Way: A ...",
  'price': '38.49',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'The Art of War',
  'price': '33.34',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'The Argonauts',
  'price': '10.93',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'The 10% Entrepreneur: Live ...',
  'price': '27.55',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Suddenly in Love (Lake ...',
  'price': '55.99',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Something More Than This',
  'price': '16.24',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Soft Apocalypse',
  'price': '26.12',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': "So You've Been Publicly ...",
  'price': '12.23',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Shoe Dog: A Memoir ...',
  'price': '23.99',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Shobu Samurai, Project Aryoku ...',
  'price': '29.06',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Secrets and Lace (Fatal ...',
  'price': '20.27',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Scarlett Epstein Hates It ...',
  'price': '43.55',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Romero and Juliet: A ...',
  'price': '36.94',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Redeeming Love',
  'price': '20.47',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Poses for Artists Volume ...',
  'price': '41.06',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Poems That Make Grown ...',
  'price': '14.19',
  'rating': 'Four',
  'stock_status': 'In stock'},
 {'name': 'Nightingale, Sing',
  'price': '38.28',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Night Sky with Exit ...',
  'price': '41.05',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Mrs. Houdini',
  'price': '30.25',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Modern Romance',
  'price': '28.26',
  'rating': 'Five',
  'stock_status': 'In stock'},
 {'name': 'Miss Peregrineâ\x80\x99s Home for ...',
  'price': '10.76',
  'rating': 'One',
  'stock_status': 'In stock'},
 {'name': 'Louisa: The Extraordinary Life ...',
  'price': '16.85',
  'rating': 'Two',
  'stock_status': 'In stock'},
 {'name': 'Little Red',
  'price': '13.47',
  'rating': 'Three',
  'stock_status': 'In stock'},
 {'name': 'Library of Souls (Miss ...',
  'price': '48.56',

In [6]:
# Length of the data_list
print(f'The length of the data_list is {len(data_list)}.')

The length of the data_list is 1000.

## 5. Convert Data to DataFrame

In [7]:
# Let's convert the data_list to the Pandas DataFrame
books_df = pd.DataFrame(data_list)
books_df.head()

                           name  price rating stock_status
0            A Light in the ...  51.77  Three     In stock
1            Tipping the Velvet  53.74    One     In stock
2                    Soumission  50.10    One     In stock
3                 Sharp Objects  47.82   Four     In stock
4  Sapiens: A Brief History ...  54.23   Five     In stock

## 6. Data Understanding

In [8]:
# Shape of the data
print(f'There are {books_df.shape[0]} rows and {books_df.shape[1]} columns in the books_df.')

There are 1000 rows and 4 columns in the books_df.

In [9]:
# Data types of the books_df
books_df.dtypes

name            str
price           str
rating          str
stock_status    str
dtype: object

In [10]:
# convert the data type of 'Price' from str to float
books_df['price'] = books_df['price'].astype('float')
books_df.dtypes

name                str
price           float64
rating              str
stock_status        str
dtype: object

In [11]:
# Let's map the ratings

books_df["rating"] = books_df["rating"].map({'One':1,
                                             'Two':2,
                                             'Three':3,
                                             'Four':4,
                                             'Five': 5})
books_df.head()

                           name  price  rating stock_status
0            A Light in the ...  51.77       3     In stock
1            Tipping the Velvet  53.74       1     In stock
2                    Soumission  50.10       1     In stock
3                 Sharp Objects  47.82       4     In stock
4  Sapiens: A Brief History ...  54.23       5     In stock

In [12]:
# Info of the data
books_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          1000 non-null   str
 1   price         1000 non-null   float64
 2   rating        1000 non-null   int64
 3   stock_status  1000 non-null   str
dtypes: float64(1), int64(1), str(2)
memory usage: 31.4 KB

In [13]:
# Statistical summary of the data
books_df.describe()

            price       rating
count  1000.00000  1000.000000
mean     35.07035     2.923000
std      14.44669     1.434967
min      10.00000     1.000000
25%      22.10750     2.000000
50%      35.98000     3.000000
75%      47.45750     4.000000
max      59.99000     5.000000

## 7. Export Data to CSV

In [14]:
# export this data to csv
books_df.to_csv("books_to_scrape.csv", index=False)

## 8. Basic Data Analysis

In [15]:
# no. of unique books
print(f'There are {books_df['name'].nunique()} unique books.')

There are 992 unique books.

In [16]:
# Top 10 Expensive books
books_df.sort_values(by = 'price', ascending = False).head(10)

                                 name  price  rating stock_status
648        The Perfect Play (Play ...  59.99       3     In stock
617            Last One Home (New ...  59.98       3     In stock
860  Civilization and Its Discontents  59.95       2     In stock
560    The Barefoot Contessa Cookbook  59.92       5     In stock
366                The Diary of a ...  59.90       3     In stock
657        The Bone Hunters (Lexy ...  59.71       3     In stock
133      Thomas Jefferson and the ...  59.64       1     In stock
387      Boar Island (Anna Pigeon ...  59.48       3     In stock
549           The Man Who Mistook ...  59.45       4     In stock
393         The Improbability of Love  59.45       1     In stock

In [17]:
# Top 10 Cheapest books
books_df.sort_values(by = 'price', ascending = True).head(10)

                                      name  price  rating stock_status
638             An Abundance of Katherines  10.00       5     In stock
501                  The Origin of Species  10.01       4     In stock
716             The Tipping Point: How ...  10.02       2     In stock
84                                Patience  10.16       3     In stock
302                   Greek Mythic History  10.23       5     In stock
558              The Fellowship of the ...  10.27       2     In stock
479                      History of Beauty  10.29       4     In stock
242  The Lucifer Effect: Understanding ...  10.40       1     In stock
434             NaNo What Now? Finding ...  10.41       4     In stock
274                           Pet Sematary  10.56       3     In stock

In [18]:
# Rating Analysis
print('Average Price by Rating')
books_df.groupby('rating')['price'].mean()

Average Price by Rating

rating
1    34.561195
2    34.810918
3    34.692020
4    36.093296
5    35.374490
Name: price, dtype: float64

In [19]:
print('No. of books by rating')
books_df.rating.value_counts().sort_values(ascending = False)

No. of books by rating

rating
1    226
3    203
5    196
2    196
4    179
Name: count, dtype: int64

In [20]:
# stock status
books_df['stock_status'].value_counts()

stock_status
In stock    1000
Name: count, dtype: int64

**All 1000 books are in stock.**

## Conclusion

In this project, I used Python and BeautifulSoup to scrape books data across multiple pages and converted the extracted information into a structured dataset for analysis.

Key concepts covered:
- HTML parsing
- Pagination handling
- Data extraction
- Export data using pandas
- Basic data analysis